// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v3.19.1
// source: grpc.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Observable } from "rxjs";
import { map } from "rxjs/operators";
import { RdfStreamFrame, RdfStreamOptions } from "./rdf";

export const protobufPackage = "eu.ostrzyciel.jelly.core.proto.v1";

/** Subscribe command sent by the client to the server. */
export interface RdfStreamSubscribe {
  /** The topic to which the client wants to subscribe (UTF-8 encoded). */
  topic: string;
  /**
   * Optional: the stream options requested by the client.
   * The server should respond with a stream that matches these options.
   * In case that is not possible, the server must respond with the
   * INVALID_ARGUMENT error.
   */
  requestedOptions: RdfStreamOptions | undefined;
}

/** Acknowledgement of receiving a stream sent by the server to the client. */
export interface RdfStreamReceived {
}

function createBaseRdfStreamSubscribe(): RdfStreamSubscribe {
  return { topic: "", requestedOptions: undefined };
}

export const RdfStreamSubscribe: MessageFns<RdfStreamSubscribe> = {
  encode(message: RdfStreamSubscribe, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.topic !== "") {
      writer.uint32(10).string(message.topic);
    }
    if (message.requestedOptions !== undefined) {
      RdfStreamOptions.encode(message.requestedOptions, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RdfStreamSubscribe {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRdfStreamSubscribe();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.topic = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.requestedOptions = RdfStreamOptions.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RdfStreamSubscribe {
    return {
      topic: isSet(object.topic) ? globalThis.String(object.topic) : "",
      requestedOptions: isSet(object.requestedOptions) ? RdfStreamOptions.fromJSON(object.requestedOptions) : undefined,
    };
  },

  toJSON(message: RdfStreamSubscribe): unknown {
    const obj: any = {};
    if (message.topic !== "") {
      obj.topic = message.topic;
    }
    if (message.requestedOptions !== undefined) {
      obj.requestedOptions = RdfStreamOptions.toJSON(message.requestedOptions);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RdfStreamSubscribe>, I>>(base?: I): RdfStreamSubscribe {
    return RdfStreamSubscribe.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RdfStreamSubscribe>, I>>(object: I): RdfStreamSubscribe {
    const message = createBaseRdfStreamSubscribe();
    message.topic = object.topic ?? "";
    message.requestedOptions = (object.requestedOptions !== undefined && object.requestedOptions !== null)
      ? RdfStreamOptions.fromPartial(object.requestedOptions)
      : undefined;
    return message;
  },
};

function createBaseRdfStreamReceived(): RdfStreamReceived {
  return {};
}

export const RdfStreamReceived: MessageFns<RdfStreamReceived> = {
  encode(_: RdfStreamReceived, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RdfStreamReceived {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRdfStreamReceived();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): RdfStreamReceived {
    return {};
  },

  toJSON(_: RdfStreamReceived): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<RdfStreamReceived>, I>>(base?: I): RdfStreamReceived {
    return RdfStreamReceived.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RdfStreamReceived>, I>>(_: I): RdfStreamReceived {
    const message = createBaseRdfStreamReceived();
    return message;
  },
};

/** Pub/Sub service for RDF streams, to be implemented by the server. */
export interface RdfStreamService {
  /** Subscribe to an RDF stream. */
  SubscribeRdf(request: RdfStreamSubscribe): Observable<RdfStreamFrame>;
  /**
   * Publish an RDF stream.
   * In case the server cannot process the stream, it must respond with
   * the INVALID_ARGUMENT error.
   */
  PublishRdf(request: Observable<RdfStreamFrame>): Promise<RdfStreamReceived>;
}

export const RdfStreamServiceServiceName = "eu.ostrzyciel.jelly.core.proto.v1.RdfStreamService";
export class RdfStreamServiceClientImpl implements RdfStreamService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || RdfStreamServiceServiceName;
    this.rpc = rpc;
    this.SubscribeRdf = this.SubscribeRdf.bind(this);
    this.PublishRdf = this.PublishRdf.bind(this);
  }
  SubscribeRdf(request: RdfStreamSubscribe): Observable<RdfStreamFrame> {
    const data = RdfStreamSubscribe.encode(request).finish();
    const result = this.rpc.serverStreamingRequest(this.service, "SubscribeRdf", data);
    return result.pipe(map((data) => RdfStreamFrame.decode(new BinaryReader(data))));
  }

  PublishRdf(request: Observable<RdfStreamFrame>): Promise<RdfStreamReceived> {
    const data = request.pipe(map((request) => RdfStreamFrame.encode(request).finish()));
    const promise = this.rpc.clientStreamingRequest(this.service, "PublishRdf", data);
    return promise.then((data) => RdfStreamReceived.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
  clientStreamingRequest(service: string, method: string, data: Observable<Uint8Array>): Promise<Uint8Array>;
  serverStreamingRequest(service: string, method: string, data: Uint8Array): Observable<Uint8Array>;
  bidirectionalStreamingRequest(service: string, method: string, data: Observable<Uint8Array>): Observable<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
