// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v3.19.1
// source: patch.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  RdfDatatypeEntry,
  RdfDefaultGraph,
  RdfIri,
  RdfLiteral,
  RdfNameEntry,
  RdfPrefixEntry,
  RdfQuad,
  RdfTriple,
} from "./rdf";

export const protobufPackage = "eu.ostrzyciel.jelly.core.proto.v1.patch";

/**
 * Type of statements in the stream.
 * This determines whether the statements are interpreted as triples or quads.
 */
export enum PatchStatementType {
  /** PATCH_STATEMENT_TYPE_UNSPECIFIED - Unspecified stream type – invalid */
  PATCH_STATEMENT_TYPE_UNSPECIFIED = 0,
  /** PATCH_STATEMENT_TYPE_TRIPLES - RDF triples */
  PATCH_STATEMENT_TYPE_TRIPLES = 1,
  /** PATCH_STATEMENT_TYPE_QUADS - RDF quads */
  PATCH_STATEMENT_TYPE_QUADS = 2,
  UNRECOGNIZED = -1,
}

export function patchStatementTypeFromJSON(object: any): PatchStatementType {
  switch (object) {
    case 0:
    case "PATCH_STATEMENT_TYPE_UNSPECIFIED":
      return PatchStatementType.PATCH_STATEMENT_TYPE_UNSPECIFIED;
    case 1:
    case "PATCH_STATEMENT_TYPE_TRIPLES":
      return PatchStatementType.PATCH_STATEMENT_TYPE_TRIPLES;
    case 2:
    case "PATCH_STATEMENT_TYPE_QUADS":
      return PatchStatementType.PATCH_STATEMENT_TYPE_QUADS;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PatchStatementType.UNRECOGNIZED;
  }
}

export function patchStatementTypeToJSON(object: PatchStatementType): string {
  switch (object) {
    case PatchStatementType.PATCH_STATEMENT_TYPE_UNSPECIFIED:
      return "PATCH_STATEMENT_TYPE_UNSPECIFIED";
    case PatchStatementType.PATCH_STATEMENT_TYPE_TRIPLES:
      return "PATCH_STATEMENT_TYPE_TRIPLES";
    case PatchStatementType.PATCH_STATEMENT_TYPE_QUADS:
      return "PATCH_STATEMENT_TYPE_QUADS";
    case PatchStatementType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * Type of the stream.
 * This determines whether each RdfPatchFrame is a complete patch by itself,
 * or part of a larger patch.
 */
export enum PatchStreamType {
  /** PATCH_STREAM_TYPE_UNSPECIFIED - Unspecified stream type – invalid */
  PATCH_STREAM_TYPE_UNSPECIFIED = 0,
  /**
   * PATCH_STREAM_TYPE_FRAME - Each RdfPatchFrame is a complete patch.
   * In this case, transactions cannot span multiple frames.
   */
  PATCH_STREAM_TYPE_FRAME = 1,
  /**
   * PATCH_STREAM_TYPE_FLAT - Entire stream is a single patch.
   * Transactions may span multiple frames.
   */
  PATCH_STREAM_TYPE_FLAT = 2,
  /**
   * PATCH_STREAM_TYPE_PUNCTUATED - Stream contains multiple patches separated by punctuation marks.
   * Patches and transactions may span multiple frames.
   * Each frame must contain at most one patch.
   */
  PATCH_STREAM_TYPE_PUNCTUATED = 3,
  UNRECOGNIZED = -1,
}

export function patchStreamTypeFromJSON(object: any): PatchStreamType {
  switch (object) {
    case 0:
    case "PATCH_STREAM_TYPE_UNSPECIFIED":
      return PatchStreamType.PATCH_STREAM_TYPE_UNSPECIFIED;
    case 1:
    case "PATCH_STREAM_TYPE_FRAME":
      return PatchStreamType.PATCH_STREAM_TYPE_FRAME;
    case 2:
    case "PATCH_STREAM_TYPE_FLAT":
      return PatchStreamType.PATCH_STREAM_TYPE_FLAT;
    case 3:
    case "PATCH_STREAM_TYPE_PUNCTUATED":
      return PatchStreamType.PATCH_STREAM_TYPE_PUNCTUATED;
    case -1:
    case "UNRECOGNIZED":
    default:
      return PatchStreamType.UNRECOGNIZED;
  }
}

export function patchStreamTypeToJSON(object: PatchStreamType): string {
  switch (object) {
    case PatchStreamType.PATCH_STREAM_TYPE_UNSPECIFIED:
      return "PATCH_STREAM_TYPE_UNSPECIFIED";
    case PatchStreamType.PATCH_STREAM_TYPE_FRAME:
      return "PATCH_STREAM_TYPE_FRAME";
    case PatchStreamType.PATCH_STREAM_TYPE_FLAT:
      return "PATCH_STREAM_TYPE_FLAT";
    case PatchStreamType.PATCH_STREAM_TYPE_PUNCTUATED:
      return "PATCH_STREAM_TYPE_PUNCTUATED";
    case PatchStreamType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface RdfPatchTransactionStart {
}

export interface RdfPatchTransactionCommit {
}

export interface RdfPatchTransactionAbort {
}

export interface RdfPatchNamespace {
  /**
   * Short name of the namespace (e.g., "ex")
   * Do NOT include the colon.
   */
  name: string;
  /**
   * IRI of the namespace (e.g., "http://example.org/").
   * Optional in the "prefix delete" (PD) operation,
   * but required in the "prefix add" (PA) operation.
   */
  value:
    | RdfIri
    | undefined;
  /** IRI */
  gIri?:
    | RdfIri
    | undefined;
  /** Blank node */
  gBnode?:
    | string
    | undefined;
  /** Default graph */
  gDefaultGraph?:
    | RdfDefaultGraph
    | undefined;
  /** Literal – only valid for generalized RDF streams */
  gLiteral?: RdfLiteral | undefined;
}

/**
 * Metadata header for RDF Patch.
 * Header rows must occur at the start of the patch frame.
 */
export interface RdfPatchHeader {
  /** Header key (required) */
  key: string;
  /** IRI */
  hIri?:
    | RdfIri
    | undefined;
  /** Blank node */
  hBnode?:
    | string
    | undefined;
  /** Literal */
  hLiteral?:
    | RdfLiteral
    | undefined;
  /** RDF-star quoted triple */
  hTripleTerm?: RdfTriple | undefined;
}

export interface RdfPatchPunctuation {
}

/** RDF Patch stream options */
export interface RdfPatchOptions {
  /** Type of statements in the stream (required) */
  statementType: PatchStatementType;
  /** Type of the stream (required) */
  streamType: PatchStreamType;
  /** Whether the stream may contain generalized triples, quads, or datasets */
  generalizedStatements: boolean;
  /** Whether the stream may contain RDF-star statements */
  rdfStar: boolean;
  /**
   * Maximum size of the name lookup table
   * (required, must be >= 8)
   */
  maxNameTableSize: number;
  /**
   * Maximum size of the prefix lookup table
   * (required if the prefix lookup is used)
   */
  maxPrefixTableSize: number;
  /**
   * Maximum size of the datatype lookup table
   * (required if datatype literals are used)
   */
  maxDatatypeTableSize: number;
  /**
   * Protocol version (required)
   * For Jelly-Patch 1.0.x (based on Jelly-RDF 1.1.x), the value must be 1.
   * For custom extensions, the value must be 10000 or higher.
   */
  version: number;
}

/** A row in an RDF Patch stream */
export interface RdfPatchRow {
  /** Stream options. Must be the first row in the stream. */
  options?:
    | RdfPatchOptions
    | undefined;
  /** Add a triple/quad statement (A) */
  statementAdd?:
    | RdfQuad
    | undefined;
  /** Delete a triple/quad statement (D) */
  statementDelete?:
    | RdfQuad
    | undefined;
  /** Add a namespace/prefix declaration (PA) */
  namespaceAdd?:
    | RdfPatchNamespace
    | undefined;
  /** Delete a namespace/prefix declaration (PD) */
  namespaceDelete?:
    | RdfPatchNamespace
    | undefined;
  /** Transaction start (TX) */
  transactionStart?:
    | RdfPatchTransactionStart
    | undefined;
  /** Transaction commit (TC) */
  transactionCommit?:
    | RdfPatchTransactionCommit
    | undefined;
  /** Transaction abort (TA) */
  transactionAbort?:
    | RdfPatchTransactionAbort
    | undefined;
  /** Entry in the name lookup table. */
  name?:
    | RdfNameEntry
    | undefined;
  /** Entry in the prefix lookup table. */
  prefix?:
    | RdfPrefixEntry
    | undefined;
  /** Entry in the datatype lookup table. */
  datatype?:
    | RdfDatatypeEntry
    | undefined;
  /** Header entry (H) */
  header?:
    | RdfPatchHeader
    | undefined;
  /**
   * Punctuation mark, only used in stream type PUNCTUATED
   * Indicates the end of a patch.
   */
  punctuation?: RdfPatchPunctuation | undefined;
}

/** A batch of RDF patch rows. */
export interface RdfPatchFrame {
  /** Patch rows */
  rows: RdfPatchRow[];
}

function createBaseRdfPatchTransactionStart(): RdfPatchTransactionStart {
  return {};
}

export const RdfPatchTransactionStart: MessageFns<RdfPatchTransactionStart> = {
  encode(_: RdfPatchTransactionStart, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RdfPatchTransactionStart {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRdfPatchTransactionStart();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): RdfPatchTransactionStart {
    return {};
  },

  toJSON(_: RdfPatchTransactionStart): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<RdfPatchTransactionStart>, I>>(base?: I): RdfPatchTransactionStart {
    return RdfPatchTransactionStart.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RdfPatchTransactionStart>, I>>(_: I): RdfPatchTransactionStart {
    const message = createBaseRdfPatchTransactionStart();
    return message;
  },
};

function createBaseRdfPatchTransactionCommit(): RdfPatchTransactionCommit {
  return {};
}

export const RdfPatchTransactionCommit: MessageFns<RdfPatchTransactionCommit> = {
  encode(_: RdfPatchTransactionCommit, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RdfPatchTransactionCommit {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRdfPatchTransactionCommit();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): RdfPatchTransactionCommit {
    return {};
  },

  toJSON(_: RdfPatchTransactionCommit): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<RdfPatchTransactionCommit>, I>>(base?: I): RdfPatchTransactionCommit {
    return RdfPatchTransactionCommit.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RdfPatchTransactionCommit>, I>>(_: I): RdfPatchTransactionCommit {
    const message = createBaseRdfPatchTransactionCommit();
    return message;
  },
};

function createBaseRdfPatchTransactionAbort(): RdfPatchTransactionAbort {
  return {};
}

export const RdfPatchTransactionAbort: MessageFns<RdfPatchTransactionAbort> = {
  encode(_: RdfPatchTransactionAbort, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RdfPatchTransactionAbort {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRdfPatchTransactionAbort();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): RdfPatchTransactionAbort {
    return {};
  },

  toJSON(_: RdfPatchTransactionAbort): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<RdfPatchTransactionAbort>, I>>(base?: I): RdfPatchTransactionAbort {
    return RdfPatchTransactionAbort.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RdfPatchTransactionAbort>, I>>(_: I): RdfPatchTransactionAbort {
    const message = createBaseRdfPatchTransactionAbort();
    return message;
  },
};

function createBaseRdfPatchNamespace(): RdfPatchNamespace {
  return {
    name: "",
    value: undefined,
    gIri: undefined,
    gBnode: undefined,
    gDefaultGraph: undefined,
    gLiteral: undefined,
  };
}

export const RdfPatchNamespace: MessageFns<RdfPatchNamespace> = {
  encode(message: RdfPatchNamespace, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.value !== undefined) {
      RdfIri.encode(message.value, writer.uint32(18).fork()).join();
    }
    if (message.gIri !== undefined) {
      RdfIri.encode(message.gIri, writer.uint32(26).fork()).join();
    }
    if (message.gBnode !== undefined) {
      writer.uint32(34).string(message.gBnode);
    }
    if (message.gDefaultGraph !== undefined) {
      RdfDefaultGraph.encode(message.gDefaultGraph, writer.uint32(42).fork()).join();
    }
    if (message.gLiteral !== undefined) {
      RdfLiteral.encode(message.gLiteral, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RdfPatchNamespace {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRdfPatchNamespace();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = RdfIri.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.gIri = RdfIri.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.gBnode = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.gDefaultGraph = RdfDefaultGraph.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.gLiteral = RdfLiteral.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RdfPatchNamespace {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      value: isSet(object.value) ? RdfIri.fromJSON(object.value) : undefined,
      gIri: isSet(object.gIri) ? RdfIri.fromJSON(object.gIri) : undefined,
      gBnode: isSet(object.gBnode) ? globalThis.String(object.gBnode) : undefined,
      gDefaultGraph: isSet(object.gDefaultGraph) ? RdfDefaultGraph.fromJSON(object.gDefaultGraph) : undefined,
      gLiteral: isSet(object.gLiteral) ? RdfLiteral.fromJSON(object.gLiteral) : undefined,
    };
  },

  toJSON(message: RdfPatchNamespace): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.value !== undefined) {
      obj.value = RdfIri.toJSON(message.value);
    }
    if (message.gIri !== undefined) {
      obj.gIri = RdfIri.toJSON(message.gIri);
    }
    if (message.gBnode !== undefined) {
      obj.gBnode = message.gBnode;
    }
    if (message.gDefaultGraph !== undefined) {
      obj.gDefaultGraph = RdfDefaultGraph.toJSON(message.gDefaultGraph);
    }
    if (message.gLiteral !== undefined) {
      obj.gLiteral = RdfLiteral.toJSON(message.gLiteral);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RdfPatchNamespace>, I>>(base?: I): RdfPatchNamespace {
    return RdfPatchNamespace.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RdfPatchNamespace>, I>>(object: I): RdfPatchNamespace {
    const message = createBaseRdfPatchNamespace();
    message.name = object.name ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? RdfIri.fromPartial(object.value)
      : undefined;
    message.gIri = (object.gIri !== undefined && object.gIri !== null) ? RdfIri.fromPartial(object.gIri) : undefined;
    message.gBnode = object.gBnode ?? undefined;
    message.gDefaultGraph = (object.gDefaultGraph !== undefined && object.gDefaultGraph !== null)
      ? RdfDefaultGraph.fromPartial(object.gDefaultGraph)
      : undefined;
    message.gLiteral = (object.gLiteral !== undefined && object.gLiteral !== null)
      ? RdfLiteral.fromPartial(object.gLiteral)
      : undefined;
    return message;
  },
};

function createBaseRdfPatchHeader(): RdfPatchHeader {
  return { key: "", hIri: undefined, hBnode: undefined, hLiteral: undefined, hTripleTerm: undefined };
}

export const RdfPatchHeader: MessageFns<RdfPatchHeader> = {
  encode(message: RdfPatchHeader, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.hIri !== undefined) {
      RdfIri.encode(message.hIri, writer.uint32(18).fork()).join();
    }
    if (message.hBnode !== undefined) {
      writer.uint32(26).string(message.hBnode);
    }
    if (message.hLiteral !== undefined) {
      RdfLiteral.encode(message.hLiteral, writer.uint32(34).fork()).join();
    }
    if (message.hTripleTerm !== undefined) {
      RdfTriple.encode(message.hTripleTerm, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RdfPatchHeader {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRdfPatchHeader();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.hIri = RdfIri.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.hBnode = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.hLiteral = RdfLiteral.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.hTripleTerm = RdfTriple.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RdfPatchHeader {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      hIri: isSet(object.hIri) ? RdfIri.fromJSON(object.hIri) : undefined,
      hBnode: isSet(object.hBnode) ? globalThis.String(object.hBnode) : undefined,
      hLiteral: isSet(object.hLiteral) ? RdfLiteral.fromJSON(object.hLiteral) : undefined,
      hTripleTerm: isSet(object.hTripleTerm) ? RdfTriple.fromJSON(object.hTripleTerm) : undefined,
    };
  },

  toJSON(message: RdfPatchHeader): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.hIri !== undefined) {
      obj.hIri = RdfIri.toJSON(message.hIri);
    }
    if (message.hBnode !== undefined) {
      obj.hBnode = message.hBnode;
    }
    if (message.hLiteral !== undefined) {
      obj.hLiteral = RdfLiteral.toJSON(message.hLiteral);
    }
    if (message.hTripleTerm !== undefined) {
      obj.hTripleTerm = RdfTriple.toJSON(message.hTripleTerm);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RdfPatchHeader>, I>>(base?: I): RdfPatchHeader {
    return RdfPatchHeader.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RdfPatchHeader>, I>>(object: I): RdfPatchHeader {
    const message = createBaseRdfPatchHeader();
    message.key = object.key ?? "";
    message.hIri = (object.hIri !== undefined && object.hIri !== null) ? RdfIri.fromPartial(object.hIri) : undefined;
    message.hBnode = object.hBnode ?? undefined;
    message.hLiteral = (object.hLiteral !== undefined && object.hLiteral !== null)
      ? RdfLiteral.fromPartial(object.hLiteral)
      : undefined;
    message.hTripleTerm = (object.hTripleTerm !== undefined && object.hTripleTerm !== null)
      ? RdfTriple.fromPartial(object.hTripleTerm)
      : undefined;
    return message;
  },
};

function createBaseRdfPatchPunctuation(): RdfPatchPunctuation {
  return {};
}

export const RdfPatchPunctuation: MessageFns<RdfPatchPunctuation> = {
  encode(_: RdfPatchPunctuation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RdfPatchPunctuation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRdfPatchPunctuation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): RdfPatchPunctuation {
    return {};
  },

  toJSON(_: RdfPatchPunctuation): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<RdfPatchPunctuation>, I>>(base?: I): RdfPatchPunctuation {
    return RdfPatchPunctuation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RdfPatchPunctuation>, I>>(_: I): RdfPatchPunctuation {
    const message = createBaseRdfPatchPunctuation();
    return message;
  },
};

function createBaseRdfPatchOptions(): RdfPatchOptions {
  return {
    statementType: 0,
    streamType: 0,
    generalizedStatements: false,
    rdfStar: false,
    maxNameTableSize: 0,
    maxPrefixTableSize: 0,
    maxDatatypeTableSize: 0,
    version: 0,
  };
}

export const RdfPatchOptions: MessageFns<RdfPatchOptions> = {
  encode(message: RdfPatchOptions, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.statementType !== 0) {
      writer.uint32(8).int32(message.statementType);
    }
    if (message.streamType !== 0) {
      writer.uint32(16).int32(message.streamType);
    }
    if (message.generalizedStatements !== false) {
      writer.uint32(24).bool(message.generalizedStatements);
    }
    if (message.rdfStar !== false) {
      writer.uint32(32).bool(message.rdfStar);
    }
    if (message.maxNameTableSize !== 0) {
      writer.uint32(72).uint32(message.maxNameTableSize);
    }
    if (message.maxPrefixTableSize !== 0) {
      writer.uint32(80).uint32(message.maxPrefixTableSize);
    }
    if (message.maxDatatypeTableSize !== 0) {
      writer.uint32(88).uint32(message.maxDatatypeTableSize);
    }
    if (message.version !== 0) {
      writer.uint32(120).uint32(message.version);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RdfPatchOptions {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRdfPatchOptions();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.statementType = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.streamType = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.generalizedStatements = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.rdfStar = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.maxNameTableSize = reader.uint32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.maxPrefixTableSize = reader.uint32();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.maxDatatypeTableSize = reader.uint32();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.version = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RdfPatchOptions {
    return {
      statementType: isSet(object.statementType) ? patchStatementTypeFromJSON(object.statementType) : 0,
      streamType: isSet(object.streamType) ? patchStreamTypeFromJSON(object.streamType) : 0,
      generalizedStatements: isSet(object.generalizedStatements)
        ? globalThis.Boolean(object.generalizedStatements)
        : false,
      rdfStar: isSet(object.rdfStar) ? globalThis.Boolean(object.rdfStar) : false,
      maxNameTableSize: isSet(object.maxNameTableSize) ? globalThis.Number(object.maxNameTableSize) : 0,
      maxPrefixTableSize: isSet(object.maxPrefixTableSize) ? globalThis.Number(object.maxPrefixTableSize) : 0,
      maxDatatypeTableSize: isSet(object.maxDatatypeTableSize) ? globalThis.Number(object.maxDatatypeTableSize) : 0,
      version: isSet(object.version) ? globalThis.Number(object.version) : 0,
    };
  },

  toJSON(message: RdfPatchOptions): unknown {
    const obj: any = {};
    if (message.statementType !== 0) {
      obj.statementType = patchStatementTypeToJSON(message.statementType);
    }
    if (message.streamType !== 0) {
      obj.streamType = patchStreamTypeToJSON(message.streamType);
    }
    if (message.generalizedStatements !== false) {
      obj.generalizedStatements = message.generalizedStatements;
    }
    if (message.rdfStar !== false) {
      obj.rdfStar = message.rdfStar;
    }
    if (message.maxNameTableSize !== 0) {
      obj.maxNameTableSize = Math.round(message.maxNameTableSize);
    }
    if (message.maxPrefixTableSize !== 0) {
      obj.maxPrefixTableSize = Math.round(message.maxPrefixTableSize);
    }
    if (message.maxDatatypeTableSize !== 0) {
      obj.maxDatatypeTableSize = Math.round(message.maxDatatypeTableSize);
    }
    if (message.version !== 0) {
      obj.version = Math.round(message.version);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RdfPatchOptions>, I>>(base?: I): RdfPatchOptions {
    return RdfPatchOptions.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RdfPatchOptions>, I>>(object: I): RdfPatchOptions {
    const message = createBaseRdfPatchOptions();
    message.statementType = object.statementType ?? 0;
    message.streamType = object.streamType ?? 0;
    message.generalizedStatements = object.generalizedStatements ?? false;
    message.rdfStar = object.rdfStar ?? false;
    message.maxNameTableSize = object.maxNameTableSize ?? 0;
    message.maxPrefixTableSize = object.maxPrefixTableSize ?? 0;
    message.maxDatatypeTableSize = object.maxDatatypeTableSize ?? 0;
    message.version = object.version ?? 0;
    return message;
  },
};

function createBaseRdfPatchRow(): RdfPatchRow {
  return {
    options: undefined,
    statementAdd: undefined,
    statementDelete: undefined,
    namespaceAdd: undefined,
    namespaceDelete: undefined,
    transactionStart: undefined,
    transactionCommit: undefined,
    transactionAbort: undefined,
    name: undefined,
    prefix: undefined,
    datatype: undefined,
    header: undefined,
    punctuation: undefined,
  };
}

export const RdfPatchRow: MessageFns<RdfPatchRow> = {
  encode(message: RdfPatchRow, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.options !== undefined) {
      RdfPatchOptions.encode(message.options, writer.uint32(10).fork()).join();
    }
    if (message.statementAdd !== undefined) {
      RdfQuad.encode(message.statementAdd, writer.uint32(18).fork()).join();
    }
    if (message.statementDelete !== undefined) {
      RdfQuad.encode(message.statementDelete, writer.uint32(26).fork()).join();
    }
    if (message.namespaceAdd !== undefined) {
      RdfPatchNamespace.encode(message.namespaceAdd, writer.uint32(34).fork()).join();
    }
    if (message.namespaceDelete !== undefined) {
      RdfPatchNamespace.encode(message.namespaceDelete, writer.uint32(42).fork()).join();
    }
    if (message.transactionStart !== undefined) {
      RdfPatchTransactionStart.encode(message.transactionStart, writer.uint32(50).fork()).join();
    }
    if (message.transactionCommit !== undefined) {
      RdfPatchTransactionCommit.encode(message.transactionCommit, writer.uint32(58).fork()).join();
    }
    if (message.transactionAbort !== undefined) {
      RdfPatchTransactionAbort.encode(message.transactionAbort, writer.uint32(66).fork()).join();
    }
    if (message.name !== undefined) {
      RdfNameEntry.encode(message.name, writer.uint32(90).fork()).join();
    }
    if (message.prefix !== undefined) {
      RdfPrefixEntry.encode(message.prefix, writer.uint32(98).fork()).join();
    }
    if (message.datatype !== undefined) {
      RdfDatatypeEntry.encode(message.datatype, writer.uint32(106).fork()).join();
    }
    if (message.header !== undefined) {
      RdfPatchHeader.encode(message.header, writer.uint32(114).fork()).join();
    }
    if (message.punctuation !== undefined) {
      RdfPatchPunctuation.encode(message.punctuation, writer.uint32(122).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RdfPatchRow {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRdfPatchRow();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.options = RdfPatchOptions.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.statementAdd = RdfQuad.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.statementDelete = RdfQuad.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.namespaceAdd = RdfPatchNamespace.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.namespaceDelete = RdfPatchNamespace.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.transactionStart = RdfPatchTransactionStart.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.transactionCommit = RdfPatchTransactionCommit.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.transactionAbort = RdfPatchTransactionAbort.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.name = RdfNameEntry.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.prefix = RdfPrefixEntry.decode(reader, reader.uint32());
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.datatype = RdfDatatypeEntry.decode(reader, reader.uint32());
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.header = RdfPatchHeader.decode(reader, reader.uint32());
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.punctuation = RdfPatchPunctuation.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RdfPatchRow {
    return {
      options: isSet(object.options) ? RdfPatchOptions.fromJSON(object.options) : undefined,
      statementAdd: isSet(object.statementAdd) ? RdfQuad.fromJSON(object.statementAdd) : undefined,
      statementDelete: isSet(object.statementDelete) ? RdfQuad.fromJSON(object.statementDelete) : undefined,
      namespaceAdd: isSet(object.namespaceAdd) ? RdfPatchNamespace.fromJSON(object.namespaceAdd) : undefined,
      namespaceDelete: isSet(object.namespaceDelete) ? RdfPatchNamespace.fromJSON(object.namespaceDelete) : undefined,
      transactionStart: isSet(object.transactionStart)
        ? RdfPatchTransactionStart.fromJSON(object.transactionStart)
        : undefined,
      transactionCommit: isSet(object.transactionCommit)
        ? RdfPatchTransactionCommit.fromJSON(object.transactionCommit)
        : undefined,
      transactionAbort: isSet(object.transactionAbort)
        ? RdfPatchTransactionAbort.fromJSON(object.transactionAbort)
        : undefined,
      name: isSet(object.name) ? RdfNameEntry.fromJSON(object.name) : undefined,
      prefix: isSet(object.prefix) ? RdfPrefixEntry.fromJSON(object.prefix) : undefined,
      datatype: isSet(object.datatype) ? RdfDatatypeEntry.fromJSON(object.datatype) : undefined,
      header: isSet(object.header) ? RdfPatchHeader.fromJSON(object.header) : undefined,
      punctuation: isSet(object.punctuation) ? RdfPatchPunctuation.fromJSON(object.punctuation) : undefined,
    };
  },

  toJSON(message: RdfPatchRow): unknown {
    const obj: any = {};
    if (message.options !== undefined) {
      obj.options = RdfPatchOptions.toJSON(message.options);
    }
    if (message.statementAdd !== undefined) {
      obj.statementAdd = RdfQuad.toJSON(message.statementAdd);
    }
    if (message.statementDelete !== undefined) {
      obj.statementDelete = RdfQuad.toJSON(message.statementDelete);
    }
    if (message.namespaceAdd !== undefined) {
      obj.namespaceAdd = RdfPatchNamespace.toJSON(message.namespaceAdd);
    }
    if (message.namespaceDelete !== undefined) {
      obj.namespaceDelete = RdfPatchNamespace.toJSON(message.namespaceDelete);
    }
    if (message.transactionStart !== undefined) {
      obj.transactionStart = RdfPatchTransactionStart.toJSON(message.transactionStart);
    }
    if (message.transactionCommit !== undefined) {
      obj.transactionCommit = RdfPatchTransactionCommit.toJSON(message.transactionCommit);
    }
    if (message.transactionAbort !== undefined) {
      obj.transactionAbort = RdfPatchTransactionAbort.toJSON(message.transactionAbort);
    }
    if (message.name !== undefined) {
      obj.name = RdfNameEntry.toJSON(message.name);
    }
    if (message.prefix !== undefined) {
      obj.prefix = RdfPrefixEntry.toJSON(message.prefix);
    }
    if (message.datatype !== undefined) {
      obj.datatype = RdfDatatypeEntry.toJSON(message.datatype);
    }
    if (message.header !== undefined) {
      obj.header = RdfPatchHeader.toJSON(message.header);
    }
    if (message.punctuation !== undefined) {
      obj.punctuation = RdfPatchPunctuation.toJSON(message.punctuation);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RdfPatchRow>, I>>(base?: I): RdfPatchRow {
    return RdfPatchRow.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RdfPatchRow>, I>>(object: I): RdfPatchRow {
    const message = createBaseRdfPatchRow();
    message.options = (object.options !== undefined && object.options !== null)
      ? RdfPatchOptions.fromPartial(object.options)
      : undefined;
    message.statementAdd = (object.statementAdd !== undefined && object.statementAdd !== null)
      ? RdfQuad.fromPartial(object.statementAdd)
      : undefined;
    message.statementDelete = (object.statementDelete !== undefined && object.statementDelete !== null)
      ? RdfQuad.fromPartial(object.statementDelete)
      : undefined;
    message.namespaceAdd = (object.namespaceAdd !== undefined && object.namespaceAdd !== null)
      ? RdfPatchNamespace.fromPartial(object.namespaceAdd)
      : undefined;
    message.namespaceDelete = (object.namespaceDelete !== undefined && object.namespaceDelete !== null)
      ? RdfPatchNamespace.fromPartial(object.namespaceDelete)
      : undefined;
    message.transactionStart = (object.transactionStart !== undefined && object.transactionStart !== null)
      ? RdfPatchTransactionStart.fromPartial(object.transactionStart)
      : undefined;
    message.transactionCommit = (object.transactionCommit !== undefined && object.transactionCommit !== null)
      ? RdfPatchTransactionCommit.fromPartial(object.transactionCommit)
      : undefined;
    message.transactionAbort = (object.transactionAbort !== undefined && object.transactionAbort !== null)
      ? RdfPatchTransactionAbort.fromPartial(object.transactionAbort)
      : undefined;
    message.name = (object.name !== undefined && object.name !== null)
      ? RdfNameEntry.fromPartial(object.name)
      : undefined;
    message.prefix = (object.prefix !== undefined && object.prefix !== null)
      ? RdfPrefixEntry.fromPartial(object.prefix)
      : undefined;
    message.datatype = (object.datatype !== undefined && object.datatype !== null)
      ? RdfDatatypeEntry.fromPartial(object.datatype)
      : undefined;
    message.header = (object.header !== undefined && object.header !== null)
      ? RdfPatchHeader.fromPartial(object.header)
      : undefined;
    message.punctuation = (object.punctuation !== undefined && object.punctuation !== null)
      ? RdfPatchPunctuation.fromPartial(object.punctuation)
      : undefined;
    return message;
  },
};

function createBaseRdfPatchFrame(): RdfPatchFrame {
  return { rows: [] };
}

export const RdfPatchFrame: MessageFns<RdfPatchFrame> = {
  encode(message: RdfPatchFrame, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.rows) {
      RdfPatchRow.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RdfPatchFrame {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRdfPatchFrame();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.rows.push(RdfPatchRow.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RdfPatchFrame {
    return { rows: globalThis.Array.isArray(object?.rows) ? object.rows.map((e: any) => RdfPatchRow.fromJSON(e)) : [] };
  },

  toJSON(message: RdfPatchFrame): unknown {
    const obj: any = {};
    if (message.rows?.length) {
      obj.rows = message.rows.map((e) => RdfPatchRow.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RdfPatchFrame>, I>>(base?: I): RdfPatchFrame {
    return RdfPatchFrame.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RdfPatchFrame>, I>>(object: I): RdfPatchFrame {
    const message = createBaseRdfPatchFrame();
    message.rows = object.rows?.map((e) => RdfPatchRow.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
